# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: 
  - bioc-release
  - bioc-devel

warnings_are_errors: false

r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes"

sudo: false
cache: packages

# BiocCheck
bioc_packages:
  - BiocCheck

# code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
  - R CMD BiocCheck .
